filename = 'build/MusicDownloader.dmg'
volume_label = 'MusicDownloader'
format = 'UDZO'
filesystem = 'HFS+'
size = None
files = ['build/musicdownloader-1.0.app']
symlinks = {}
icon = '/Users/zhangmingfeng/py-dl/venv/lib/python3.14/site-packages/freeze_core/icons/setup.icns'
background = None
show_status_bar = False
show_tab_view = False
show_pathbar = False
show_sidebar = False
sidebar_width = None
show_icon_preview = False
include_icon_view_settings = 'auto'
include_list_view_settings = 'auto'
arrange_by = None
grid_offset = (0, 0)
grid_spacing = 100
scroll_position = (0, 0)
label_pos = 'bottom'
text_size = 16
icon_size = 128
list_sort_by = None
list_use_relative_dates = None
list_calculate_all_sizes = None
license = None
